define(function () {
	var CheatConstants = {
		
		CHEAT_NAME_CHEATLIST: "cheatlist",
		CHEAT_NAME_SPEED: "speed",
		CHEAT_NAME_AUTOPLAY: "autoplay",
		CHEAT_NAME_TIME: "time",
		CHEAT_NAME_RES: "res",
		CHEAT_NAME_SUPPLIES: "supplies",
		CHEAT_NAME_MATERIALS: "materials",
		CHEAT_NAME_VISION: "vision",
		CHEAT_NAME_EVIDENCE: "evidence",
		CHEAT_NAME_RUMOURS: "rumours",
		CHEAT_NAME_FAVOUR: "favour",
		CHEAT_NAME_POPULATION: "pop",
		CHEAT_NAME_WORKERS: "workers",
		CHEAT_NAME_STAMINA: "stamina",
		CHEAT_NAME_SET_STAMINA: "setStamina",
		CHEAT_NAME_POS: "pos",
		CHEAT_NAME_LEVEL: "gotolevel",
		CHEAT_NAME_HEAL: "heal",
		CHEAT_NAME_INJURY: "injury",
		CHEAT_NAME_BUILDING: "building",
		CHEAT_NAME_TECH: "tech",
		CHEAT_NAME_TECHS: "techs",
		CHEAT_NAME_BLUEPRINT: "blueprint",
		CHEAT_NAME_BLUEPRINTS: "blueprints",
		CHEAT_NAME_TRADE_PARTNERS: "tradepartners",
		CHEAT_NAME_TRADE_PARTNER: "tradepartner",
		CHEAT_NAME_WORKSHOPS: "workshops",
		CHEAT_NAME_ITEM: "item",
		CHEAT_NAME_FOLLOWER: "follower",
		CHEAT_NAME_EQUIP_BEST: "equipBest",
		CHEAT_NAME_BREAK_ITEM: "breakItem",
		CHEAT_NAME_PERK: "perk",
		CHEAT_NAME_REVEAL_MAP: "map",
		CHEAT_NAME_DEBUG_MAP: "debugMap",
		CHEAT_NAME_SCOUT_LEVEL: "scoutLevel",
		CHEAT_NAME_SCAVENGE: "scavenge",
		CHEAT_NAME_TRADER: "trader",
		CHEAT_NAME_RECRUIT: "recruit",
		CHEAT_NAME_RAID: "raid",
		CHEAT_NAME_RESET_BUILDING_SPOTS: "resetBuildingSpots",
		
	};
	return CheatConstants;
});
