define(['ash'
], function (Ash) {

	var LevelConstants = {
		
		UNCAMPABLE_LEVEL_TYPE_RADIATION: "UNCAMPABLE_LEVEL_TYPE_RADIATION",
		UNCAMPABLE_LEVEL_TYPE_POLLUTION: "UNCAMPABLE_LEVEL_TYPE_POLLUTION",
		UNCAMPABLE_LEVEL_TYPE_SUPERSTITION: "UNCAMPABLE_LEVEL_TYPE_SUPERSTITION",
		
	};
	return LevelConstants;
});
