define(['ash'], function (Ash) {

	let MovementConstants = {
	
		BLOCKER_TYPE_GAP: 1,
		BLOCKER_TYPE_GANG: 3,
		BLOCKER_TYPE_DEBRIS: 4,
		BLOCKER_TYPE_WASTE_RADIOACTIVE: 5,
		BLOCKER_TYPE_WASTE_TOXIC: 6,
		
		PASSAGE_TYPE_HOLE: 1,
		PASSAGE_TYPE_ELEVATOR: 2,
		PASSAGE_TYPE_STAIRWELL: 3,
		PASSAGE_TYPE_BLOCKED: 4,

		DESPAIR_TYPE_HUNGRER: "hunger",
		DESPAIR_TYPE_THIRST: "thirst",
		DESPAIR_TYPE_STAMINA: "stamina",
		DESPAIR_TYPE_MOVEMENT: "movement",
	
	};
	
	return MovementConstants;
	
});
